# =============================================
# Build config
# =============================================

root:             ./
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets